package main

import (
	"fmt"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/dnspatch/dnspatch/internal/config"
	"github.com/dnspatch/dnspatch/internal/paramspec"
	"github.com/dnspatch/dnspatch/plugin"
)

const (
	// placeholder stands in for a required string that has no `example` tag.
	// It is meant to be noticed and replaced.
	placeholder = "CHANGE_ME"

	commentWidth = 78
)

var (
	bareKey      = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)
	durationType = reflect.TypeFor[time.Duration]()
)

// renderExample builds a configuration file to copy and edit: a definition of
// every plugin with its required parameters filled with placeholders, its
// optional ones commented out with their defaults, and one instance that ties
// the first retriever to the first provider. known marks the plugins that only
// the full build has; their definitions say so.
func renderExample(retrievers, providers, notifiers map[string]reflect.Type, known []plugin.Known) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# Code generated by cmd/gendoc; DO NOT EDIT.\n")
	b.WriteString("#\n")
	b.WriteString("# dnspatch example configuration. Copy it to dnspatch.toml, replace the\n")
	b.WriteString("# placeholders, and delete the definitions you do not use.\n")
	b.WriteString("#\n")
	b.WriteString("# Uncommented parameters are required. A commented parameter is optional and\n")
	b.WriteString("# shows its default; uncomment it to change it. Every parameter is described in\n")
	b.WriteString("# docs/PARAMETERS.md. A value such as ${NAME} is read from the environment.\n")
	b.WriteString("#\n")
	b.WriteString("# This file is generated from plugin struct tags, so manual edits are\n")
	b.WriteString("# overwritten. After changing a plugin configuration, run `go generate ./...`.\n\n")

	b.WriteString("# How often instances check the address. An instance can set its own.\n")
	fmt.Fprintf(&b, "interval = %s\n\n", tomlString(shortDuration(config.DefaultInterval)))

	retrieverNames, providerNames := sortedNames(retrievers), sortedNames(providers)
	extra := extraSet(known)

	if err := writeDefinitions(&b, "retriever", "Retrievers: where the current address comes from.", retrievers, retrieverNames, extra); err != nil {
		return nil, err
	}

	if err := writeDefinitions(&b, "provider", "Providers: where the address is published.", providers, providerNames, extra); err != nil {
		return nil, err
	}

	if err := writeNotify(&b, notifiers); err != nil {
		return nil, err
	}

	writeInstance(&b, retrieverNames, providerNames, sortedNames(notifiers))

	return []byte(strings.TrimRight(b.String(), "\n") + "\n"), nil
}

// writeDefinitions writes one [<kind>.<name>] table per plugin, with a note
// above the ones that only the full build has. kind is the plugin.Kind value.
func writeDefinitions(b *strings.Builder, kind, title string, plugins map[string]reflect.Type, names []string, extra map[[2]string]bool) error {
	writeBanner(b, title)

	for _, name := range names {
		if !bareKey.MatchString(name) {
			return fmt.Errorf("%s %q: the name cannot be used as a bare TOML key", kind, name)
		}

		params, err := describe(plugins[name])
		if err != nil {
			return fmt.Errorf("%s %q: %w", kind, name, err)
		}

		if extra[[2]string{kind, name}] {
			fmt.Fprintf(b, "# Full build only (the -full image or binary, or the %q build tag): the\n# lightweight build rejects a config that uses it.\n", name)
		}

		fmt.Fprintf(b, "[%s.%s]\ntype = %s\n\n", kind, name, tomlString(name))

		for _, p := range params {
			if err := writeParam(b, p, false); err != nil {
				return fmt.Errorf("%s %q: %w", kind, name, err)
			}
		}
	}

	return nil
}

// writeParam writes one parameter with the first sentence of its description.
// A required parameter is left active, and an optional one is commented out;
// commentOut comments out the required ones too.
func writeParam(b *strings.Builder, p param, commentOut bool) error {
	if !bareKey.MatchString(strings.ReplaceAll(p.name, ".", "-")) {
		return fmt.Errorf("parameter %q cannot be written as a bare TOML key", p.name)
	}

	// The parameters of an optional table are only used once the table is
	// written, so they stay commented out even when required.
	active := p.required && p.optionalTable == "" && !commentOut

	value, err := exampleValue(p)
	if err != nil {
		return fmt.Errorf("parameter %q: %w", p.name, err)
	}

	text := summary(p.doc)

	switch {
	case p.required && p.optionalTable != "":
		text = strings.TrimSpace(text + " Required once " + p.optionalTable + " is set.")
	case p.required && commentOut:
		// A commented parameter cannot show it is required by being active.
		text = strings.TrimRight(text, ".") + ". Required."
	}

	for _, line := range wrap(text, commentWidth-2) {
		b.WriteString("# " + line + "\n")
	}

	prefix := "# "
	if active {
		prefix = ""
	}
	fmt.Fprintf(b, "%s%s = %s\n\n", prefix, p.name, value)

	return nil
}

// exampleValue picks the value shown for a parameter. A required parameter
// shows its example or a placeholder, since it has to be edited anyway; an
// optional one shows its default, so that uncommenting it changes nothing
// until the reader edits it, and falls back to the example or the zero value.
func exampleValue(p param) (string, error) {
	switch {
	case p.required && p.hasExample:
		return literal(p.typ, p.example)
	case p.hasDefault:
		return literal(p.typ, p.defaultVal)
	case p.hasExample:
		return literal(p.typ, p.example)
	case p.required && isPlainString(p.typ):
		return tomlString(placeholder), nil
	case p.required:
		return "", fmt.Errorf("a required parameter of type %s needs an example tag", p.typ)
	default:
		return zeroLiteral(p.typ)
	}
}

// writeInstance writes an instance using the first retriever and provider, and
// shows how it would pick notifiers when there are any.
func writeInstance(b *strings.Builder, retrieverNames, providerNames, notifierNames []string) {
	writeBanner(b, "Instances: each one ties one or two retrievers to the providers it updates.")

	if len(retrieverNames) == 0 || len(providerNames) == 0 {
		b.WriteString("# No retriever or no provider is registered, so there is no instance to show.\n")
		return
	}

	b.WriteString("# Add more [[instance.provider]] tables to update several providers. Parameters\n")
	b.WriteString("# set next to a ref override the definition, for example another zone.\n")
	b.WriteString("[[instance]]\n")
	b.WriteString("name = \"home\"\n")

	if len(notifierNames) > 0 {
		b.WriteString("# The notifiers this instance publishes to, by the name of their [notify.<name>]\n")
		b.WriteString("# definition. Without it an instance publishes to every notifier you define;\n")
		b.WriteString("# an empty list, [], publishes to none. To override the events of a notifier for\n")
		b.WriteString("# this instance, use [[instance.notify]] tables with ref and events instead.\n")
		fmt.Fprintf(b, "# notify = [%s]\n", tomlString(notifierNames[0]))
	}

	b.WriteString("\n")
	fmt.Fprintf(b, "[[instance.retriever]]\nref = %s\n\n", tomlString(retrieverNames[0]))
	b.WriteString("# A second [[instance.retriever]] table adds a retriever for the other address\n")
	b.WriteString("# family; each instance accepts one or two retrievers, one per family.\n")
	fmt.Fprintf(b, "[[instance.provider]]\nref = %s\n", tomlString(providerNames[0]))
}

// writeNotify writes a [notify.<name>] definition for every notifier, commented
// out: they only work on a build with a notifier compiled in (the full image or
// binary), and the lightweight build rejects a config whose instances use one,
// so leaving it active would make the example unusable there. A build with no
// notifier registered has nothing to show, and the section is left out.
func writeNotify(b *strings.Builder, notifiers map[string]reflect.Type) error {
	if len(notifiers) == 0 {
		return nil
	}

	writeBanner(b, "Notifiers: full build only (the -full image or binary).")

	b.WriteString("# Publishes a JSON event to a message broker, by default whenever an instance\n")
	b.WriteString("# flips between success and failure, to the channel <topic_prefix><instance>.\n")
	b.WriteString("# The \"events\" key chooses which events: status, provider_status,\n")
	b.WriteString("# retriever_status, ip_change, cycle and lifecycle. The lightweight build rejects\n")
	b.WriteString("# a config whose instances use a notifier. See the Monitoring page of the\n")
	b.WriteString("# documentation.\n")
	b.WriteString("#\n")
	b.WriteString("# Each [notify.<name>] definition is one broker connection, shared by the\n")
	b.WriteString("# instances that publish to it. Define several to reach several brokers, of\n")
	b.WriteString("# different types or of one type with different addresses, and name them in the\n")
	b.WriteString("# notify list of an instance.\n")
	b.WriteString("#\n")
	b.WriteString("# Each definition below is a template for one notifier: uncomment it, together\n")
	b.WriteString("# with the parameters you set and at least the ones marked Required.\n\n")

	for _, name := range sortedNames(notifiers) {
		if !bareKey.MatchString(name) {
			return fmt.Errorf("notifier %q: the name cannot be used as a bare TOML key", name)
		}

		params, err := describe(notifiers[name])
		if err != nil {
			return fmt.Errorf("notifier %q: %w", name, err)
		}

		fmt.Fprintf(b, "# [notify.%s]\n# type = %s\n# events = [\"status\"]   # optional, this is the default\n\n", name, tomlString(name))

		for _, p := range params {
			if err := writeParam(b, p, true); err != nil {
				return fmt.Errorf("notifier %q: %w", name, err)
			}
		}
	}

	return nil
}

func writeBanner(b *strings.Builder, title string) {
	rule := "# " + strings.Repeat("-", commentWidth-2) + "\n"

	b.WriteString(rule)
	b.WriteString("# " + title + "\n")
	b.WriteString(rule)
	b.WriteString("\n")
}

// literal renders a tag value as a TOML value of the parameter's type. Slices
// and maps take the tag value as TOML text, since there is no better way to
// write one in a tag.
func literal(t reflect.Type, raw string) (string, error) {
	if t == durationType {
		if _, err := time.ParseDuration(raw); err != nil {
			return "", fmt.Errorf("%q is not a duration", raw)
		}

		return tomlString(raw), nil
	}

	if isText(t) {
		return tomlString(raw), nil
	}

	switch t.Kind() {
	case reflect.Bool:
		v, err := strconv.ParseBool(raw)
		if err != nil {
			return "", fmt.Errorf("%q is not a boolean", raw)
		}

		return strconv.FormatBool(v), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v, err := strconv.ParseInt(raw, 10, 64)
		if err != nil {
			return "", fmt.Errorf("%q is not an integer", raw)
		}

		return strconv.FormatInt(v, 10), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		v, err := strconv.ParseUint(raw, 10, 64)
		if err != nil {
			return "", fmt.Errorf("%q is not a non-negative integer", raw)
		}

		return strconv.FormatUint(v, 10), nil
	case reflect.Float32, reflect.Float64:
		v, err := strconv.ParseFloat(raw, 64)
		if err != nil {
			return "", fmt.Errorf("%q is not a number", raw)
		}

		text := strconv.FormatFloat(v, 'f', -1, 64)
		if !strings.Contains(text, ".") {
			text += ".0"
		}

		return text, nil
	case reflect.Slice, reflect.Map:
		return raw, nil
	default:
		return "", fmt.Errorf("type %s has no TOML form", t)
	}
}

// zeroLiteral renders the empty value of a type, for a commented-out
// parameter that has neither a default nor an example.
func zeroLiteral(t reflect.Type) (string, error) {
	switch {
	case t == durationType:
		return `"0s"`, nil
	case isText(t):
		return `""`, nil
	}

	switch t.Kind() {
	case reflect.Bool:
		return "false", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "0", nil
	case reflect.Float32, reflect.Float64:
		return "0.0", nil
	case reflect.Slice:
		return "[]", nil
	case reflect.Map:
		return "{}", nil
	default:
		return "", fmt.Errorf("type %s has no TOML form", t)
	}
}

// isText reports whether a type is written as a TOML string: a string, or a
// type such as netip.Addr that parses itself from text.
func isText(t reflect.Type) bool {
	return t.Kind() == reflect.String || paramspec.ParsesText(t)
}

// isPlainString reports whether a type is a string that takes any text, which
// is what makes a placeholder a sensible value for it.
func isPlainString(t reflect.Type) bool {
	return t.Kind() == reflect.String && t != durationType
}

// tomlString writes text as a TOML basic string.
func tomlString(text string) string {
	var b strings.Builder

	b.WriteByte('"')

	for _, r := range text {
		switch {
		case r == '"':
			b.WriteString(`\"`)
		case r == '\\':
			b.WriteString(`\\`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\t':
			b.WriteString(`\t`)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, `\u%04X`, r)
		default:
			b.WriteRune(r)
		}
	}

	b.WriteByte('"')

	return b.String()
}

// shortDuration writes a duration the way a person would: 5m, not 5m0s.
func shortDuration(d time.Duration) string {
	text := d.String()

	if strings.HasSuffix(text, "m0s") {
		text = strings.TrimSuffix(text, "0s")
	}

	if strings.HasSuffix(text, "h0m") {
		text = strings.TrimSuffix(text, "0m")
	}

	return text
}

// summary returns the first sentence of a description, so that a template
// stays short and the full text stays in docs/PARAMETERS.md. A sentence ends at
// a period followed by a space and a capital letter.
func summary(doc string) string {
	doc = strings.Join(strings.Fields(doc), " ")

	for i := 0; i+2 < len(doc); i++ {
		if doc[i] == '.' && doc[i+1] == ' ' && unicode.IsUpper(rune(doc[i+2])) {
			return doc[:i+1]
		}
	}

	return doc
}

// wrap breaks text into lines of at most width characters, without splitting
// words.
func wrap(text string, width int) []string {
	var (
		lines []string
		line  string
	)

	for _, word := range strings.Fields(text) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= width:
			line += " " + word
		default:
			lines = append(lines, line)
			line = word
		}
	}

	if line != "" {
		lines = append(lines, line)
	}

	return lines
}
