package main

import (
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/dnspatch/dnspatch/plugin"
)

type baseConfig struct {
	Timeout string `toml:"timeout" default:"10s" doc:"Request timeout"`
}

// sampleConfig uses every feature of the configuration struct that the
// decoder understands.
type sampleConfig struct {
	Token  string `toml:"token,required" doc:"API token"`
	Region string
	Secret string     `toml:"-"`
	hidden string     //nolint:unused // exercises the skipping of unexported fields
	Addr   netip.Addr `toml:"addr" doc:"A leaf struct is one parameter, not a table"`
	Auth   struct {
		User string `toml:"user,required" doc:"Login"`
	} `toml:"auth"`
	Extra *struct {
		Key string `toml:"key,required" doc:"Key of the optional block"`
	} `toml:"extra"`

	baseConfig
}

func TestDescribeCoversEveryKindOfField(t *testing.T) {
	params, err := describe(reflect.TypeFor[sampleConfig]())
	if err != nil {
		t.Fatal(err)
	}

	str, addr := reflect.TypeFor[string](), reflect.TypeFor[netip.Addr]()

	want := []param{
		{name: "token", required: true, doc: "API token", typ: str},
		{name: "region", typ: str},
		{name: "addr", doc: "A leaf struct is one parameter, not a table", typ: addr},
		{name: "auth.user", required: true, doc: "Login", typ: str},
		{name: "extra.key", required: true, doc: "Key of the optional block", typ: str, optionalTable: "extra"},
		{name: "timeout", defaultVal: "10s", hasDefault: true, doc: "Request timeout", typ: str},
	}

	if !reflect.DeepEqual(params, want) {
		t.Errorf("describe:\n got %+v\nwant %+v", params, want)
	}
}

// The documentation is only worth having if it names the parameters the
// decoder accepts and demands, so the two are checked against each other.
func TestDescribeAgreesWithDecode(t *testing.T) {
	params, err := describe(reflect.TypeFor[sampleConfig]())
	if err != nil {
		t.Fatal(err)
	}

	for _, p := range params {
		_, err := plugin.Decode[sampleConfig](nestedParams(p.name))
		if err != nil && strings.Contains(err.Error(), "unknown parameter") {
			t.Errorf("documented parameter %q is unknown to Decode: %v", p.name, err)
		}
	}

	// The decoder reports the required parameters of a nested table only once
	// the top-level ones are satisfied, hence two rounds.
	given := map[string]any{}
	for _, p := range params {
		if p.required && !strings.Contains(p.name, ".") {
			given[p.name] = "x"
		}
	}

	rounds := []struct {
		name   string
		given  map[string]any
		nested bool
	}{
		{"top level", map[string]any{}, false},
		{"nested", given, true},
	}

	for _, round := range rounds {
		_, err := plugin.Decode[sampleConfig](round.given)
		if err == nil {
			t.Fatalf("%s: Decode accepted the configuration although some parameters are required", round.name)
		}

		for _, p := range params {
			if strings.Contains(p.name, ".") != round.nested {
				continue
			}

			reported := strings.Contains(err.Error(), fmt.Sprintf("%q is required", p.name))
			mustBe := p.required && p.optionalTable == ""

			if reported != mustBe {
				t.Errorf("%s: parameter %q: Decode reports it missing = %v, documentation says required = %v",
					round.name, p.name, reported, mustBe)
			}
		}
	}
}

// nestedParams builds the raw parameters that set one dotted name.
func nestedParams(name string) map[string]any {
	head, tail, nested := strings.Cut(name, ".")
	if !nested {
		return map[string]any{head: "x"}
	}

	return map[string]any{head: nestedParams(tail)}
}

func TestDescribeRejectsAmbiguousConfigurations(t *testing.T) {
	type duplicate struct {
		A string `toml:"name"`
		B string `toml:"NAME"`
	}

	tests := map[string]reflect.Type{
		"duplicate name": reflect.TypeFor[duplicate](),
		"not a struct":   reflect.TypeFor[string](),
	}

	for name, typ := range tests {
		t.Run(name, func(t *testing.T) {
			if _, err := describe(typ); err == nil {
				t.Error("describe accepted the type")
			}
		})
	}
}

type alphaConfig struct {
	Zone string `toml:"zone,required" doc:"Zone | with a pipe"`
	Mode string `toml:"mode" default:"" doc:"Line one.\nLine two."`
	Note string "toml:\"note\" default:\"a`b\""
}

type betaConfig struct {
	Extra *struct {
		Key string `toml:"key,required" doc:"Key"`
	} `toml:"extra"`
}

func TestRenderOutput(t *testing.T) {
	got, err := render(
		map[string]reflect.Type{"beta": reflect.TypeFor[betaConfig]()},
		map[string]reflect.Type{"alpha": reflect.TypeFor[alphaConfig](), "beta": reflect.TypeFor[struct{}]()},
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}

	want := "<!-- Code generated by cmd/gendoc; DO NOT EDIT. -->\n" +
		"\n" +
		"# Plugin parameters\n" +
		"\n" +
		"This file is generated from plugin struct tags, so manual edits are\n" +
		"overwritten. After changing a plugin configuration, run `go generate ./...`.\n" +
		"For a configuration to start from, copy [dnspatch.toml.example](https://github.com/dnspatch/dnspatch/blob/main/dnspatch.toml.example).\n" +
		"\n" +
		"## Contents\n" +
		"\n" +
		"- [Retrievers](#retrievers)\n" +
		"  - [beta](#retriever-beta)\n" +
		"- [Providers](#providers)\n" +
		"  - [alpha](#provider-alpha)\n" +
		"  - [beta](#provider-beta)\n" +
		"- [Notifiers](#notifiers)\n" +
		"\n" +
		"## Retrievers\n" +
		"\n" +
		"### Retriever `beta`\n" +
		"\n" +
		"| Parameter | Required | Default | Description |\n" +
		"|-----------|----------|---------|-------------|\n" +
		"| `extra.key` | if `extra` is set | — | Key |\n" +
		"\n" +
		"## Providers\n" +
		"\n" +
		"### Provider `alpha`\n" +
		"\n" +
		"| Parameter | Required | Default | Description |\n" +
		"|-----------|----------|---------|-------------|\n" +
		"| `zone` | yes | — | Zone \\| with a pipe |\n" +
		"| `mode` | no | `\"\"` | Line one. Line two. |\n" +
		"| `note` | no | `` a`b `` | _No description._ |\n" +
		"\n" +
		"### Provider `beta`\n" +
		"\n" +
		"No parameters.\n" +
		"\n" +
		"## Notifiers\n" +
		"\n" +
		"No notifiers are registered.\n"

	if string(got) != want {
		t.Errorf("render:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderMarksRequiredParametersOfOptionalTables(t *testing.T) {
	type config struct {
		Extra *struct {
			Key string `toml:"key,required" doc:"Key"`
		} `toml:"extra"`
	}

	got, err := render(nil, map[string]reflect.Type{"p": reflect.TypeFor[config]()}, nil)
	if err != nil {
		t.Fatal(err)
	}

	if want := "| `extra.key` | if `extra` is set | — | Key |"; !strings.Contains(string(got), want) {
		t.Errorf("no row %q in:\n%s", want, got)
	}
}

func TestRenderWithoutPlugins(t *testing.T) {
	got, err := render(nil, nil, nil)
	if err != nil {
		t.Fatal(err)
	}

	for _, want := range []string{"## Retrievers\n\nNo retrievers are registered.", "## Providers\n\nNo providers are registered."} {
		if !strings.Contains(string(got), want) {
			t.Errorf("no %q in:\n%s", want, got)
		}
	}
}

// Map iteration order is random, so the same input is rendered many times.
func TestRenderIsRepeatable(t *testing.T) {
	plugins := make(map[string]reflect.Type)
	for _, name := range []string{"e", "b", "d", "a", "c", "g", "f"} {
		plugins[name] = reflect.TypeFor[alphaConfig]()
	}

	first, err := render(plugins, plugins, nil)
	if err != nil {
		t.Fatal(err)
	}

	for range 50 {
		again, err := render(plugins, plugins, nil)
		if err != nil {
			t.Fatal(err)
		}

		if string(again) != string(first) {
			t.Fatal("two renders of the same plugins differ")
		}
	}

	if strings.Index(string(first), "### Provider `a`") > strings.Index(string(first), "### Provider `b`") {
		t.Error("plugins are not sorted by name")
	}
}

func TestRenderNamesTheBadPlugin(t *testing.T) {
	_, err := render(nil, map[string]reflect.Type{"broken": reflect.TypeFor[string]()}, nil)
	if err == nil || !strings.Contains(err.Error(), `provider "broken"`) {
		t.Errorf("error %v does not name the plugin", err)
	}
}

func TestRunWritesBothFilesAndCreatesTheirDirectories(t *testing.T) {
	dir := t.TempDir()
	docs, example := filepath.Join(dir, "docs", "PARAMETERS.md"), filepath.Join(dir, "etc", "dnspatch.toml.example")

	err := run(docs, example, "")
	if incomplete := checkComplete(plugin.Default); incomplete != nil {
		// A build without some plugins must refuse to write, and write nothing.
		if err == nil {
			t.Fatal("run succeeded in a build that lacks plugins")
		}

		if _, statErr := os.Stat(docs); statErr == nil {
			t.Error("run wrote the reference although it failed")
		}

		return
	}

	if err != nil {
		t.Fatal(err)
	}

	tests := map[string][]string{
		docs:    {"### Retriever `ifconfigco`", "### Provider `regru`"},
		example: {"[retriever.ifconfigco]", "[provider.regru]"},
	}

	for path, wants := range tests {
		got, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}

		for _, want := range wants {
			if !strings.Contains(string(got), want) {
				t.Errorf("%s lacks %q", filepath.Base(path), want)
			}
		}
	}
}

// The check that CONTRIBUTING.md asks a contributor to keep green: a change to
// a plugin configuration without go generate fails the ordinary test run, in
// CI as well as locally.
//
// The files document every plugin, so the check needs a build that has them
// all: without the full tag it is skipped here, and CI runs it with the tag.
func TestCommittedFilesAreCurrent(t *testing.T) {
	if err := checkComplete(plugin.Default); err != nil {
		t.Skip(err)
	}

	retrievers, providers, notifiers := plugin.Default.RetrieverConfigTypes(), plugin.Default.ProviderConfigTypes(), plugin.Default.NotifierConfigTypes()

	files := map[string]func(retrievers, providers, notifiers map[string]reflect.Type) ([]byte, error){
		"docs/PARAMETERS.md":    render,
		"dnspatch.toml.example": renderExample,
	}

	for name, generate := range files {
		t.Run(name, func(t *testing.T) {
			want, err := generate(retrievers, providers, notifiers)
			if err != nil {
				t.Fatal(err)
			}

			got, err := os.ReadFile(filepath.Join("..", "..", filepath.FromSlash(name)))
			if err != nil {
				t.Fatal(err)
			}

			if string(got) != string(want) {
				t.Errorf("%s is out of date; run go generate ./... and commit the result", name)
			}
		})
	}
}

func TestRenderListsNotifiers(t *testing.T) {
	got, err := render(nil, nil, map[string]reflect.Type{"broker": reflect.TypeFor[alphaConfig]()})
	if err != nil {
		t.Fatal(err)
	}

	for _, want := range []string{"- [Notifiers](#notifiers)\n  - [broker](#notifier-broker)\n", "## Notifiers\n\n### Notifier `broker`\n"} {
		if !strings.Contains(string(got), want) {
			t.Errorf("output lacks %q:\n%s", want, got)
		}
	}
}

func TestCheckCompleteNamesWhatIsMissing(t *testing.T) {
	r := plugin.NewRegistry()

	if err := checkComplete(r); err == nil {
		t.Error("checkComplete accepted a registry that declares nothing")
	}

	r.Declare(plugin.KindProvider, "here", "")
	r.Declare(plugin.KindNotifier, "gone", "")
	plugin.RegisterProviderIn(r, "here", func(struct{}) (plugin.Provider, error) { return nil, nil })

	err := checkComplete(r)
	if err == nil || !strings.Contains(err.Error(), "notifier gone") || strings.Contains(err.Error(), "here") {
		t.Errorf("checkComplete error = %v, want it to name only the notifier gone", err)
	}

	plugin.RegisterNotifierIn(r, "gone", func(struct{ plugin.NotifierCommon }) (plugin.Notifier, error) { return nil, nil })

	if err := checkComplete(r); err != nil {
		t.Errorf("checkComplete of a complete registry = %v", err)
	}
}
