package main

import (
	"fmt"
	"maps"
	"reflect"
	"slices"
	"strings"

	"github.com/dnspatch/dnspatch/plugin"
)

const noDescription = "_No description._"

// section is one plugin kind in the generated document.
type section struct {
	title string
	// kind is the singular used in the heading of each plugin, which keeps a
	// retriever and a provider of the same name apart in the table of contents.
	kind    string
	pkind   plugin.Kind
	plugins map[string]reflect.Type
}

// extraSet maps the plugins that the default build leaves out, by kind and
// name, to true. A plugin the catalog does not list counts as part of the
// default build.
func extraSet(known []plugin.Known) map[[2]string]bool {
	extra := make(map[[2]string]bool, len(known))

	for _, k := range known {
		extra[[2]string{string(k.Kind), k.Name}] = k.Extra
	}

	return extra
}

// render builds the whole document. Plugins are listed by name and parameters
// in declaration order, so the output does not depend on map iteration order
// and repeated runs give the same bytes. known marks the plugins that only the
// full build has, and each of them gets a note, so that a reader does not learn
// it from an error at startup.
func render(retrievers, providers, notifiers map[string]reflect.Type, known []plugin.Known) ([]byte, error) {
	sections := []section{
		{title: "Retrievers", kind: "Retriever", pkind: plugin.KindRetriever, plugins: retrievers},
		{title: "Providers", kind: "Provider", pkind: plugin.KindProvider, plugins: providers},
		{title: "Notifiers", kind: "Notifier", pkind: plugin.KindNotifier, plugins: notifiers},
	}
	extra := extraSet(known)

	var b strings.Builder

	b.WriteString("<!-- Code generated by cmd/gendoc; DO NOT EDIT. -->\n\n")
	b.WriteString("# Plugin parameters\n\n")
	b.WriteString("This file is generated from plugin struct tags, so manual edits are\n")
	b.WriteString("overwritten. After changing a plugin configuration, run `go generate ./...`.\n")
	b.WriteString("For a configuration to start from, copy [dnspatch.toml.example](https://github.com/dnspatch/dnspatch/blob/main/dnspatch.toml.example).\n\n")

	writeContents(&b, sections)

	for _, s := range sections {
		fmt.Fprintf(&b, "## %s\n\n", s.title)

		names := sortedNames(s.plugins)
		if len(names) == 0 {
			fmt.Fprintf(&b, "No %s are registered.\n\n", strings.ToLower(s.title))
			continue
		}

		for _, name := range names {
			params, err := describe(s.plugins[name])
			if err != nil {
				return nil, fmt.Errorf("%s %q: %w", strings.ToLower(s.kind), name, err)
			}

			fmt.Fprintf(&b, "### %s\n\n", heading(s.kind, name))

			if extra[[2]string{string(s.pkind), name}] {
				fmt.Fprintf(&b, "> **Full build only.** The lightweight build rejects a config that uses it. Use the `-full` image or binary, or build with the `%s` or `full` tag; see [Installation](installation.md#lightweight-and-full-builds).\n\n", name)
			}

			writeTable(&b, params)
		}
	}

	return []byte(strings.TrimRight(b.String(), "\n") + "\n"), nil
}

// writeContents writes the table of contents linking to every section and
// plugin.
func writeContents(b *strings.Builder, sections []section) {
	b.WriteString("## Contents\n\n")

	for _, s := range sections {
		fmt.Fprintf(b, "- [%s](#%s)\n", s.title, anchor(s.title))

		for _, name := range sortedNames(s.plugins) {
			fmt.Fprintf(b, "  - [%s](#%s)\n", name, anchor(heading(s.kind, name)))
		}
	}

	b.WriteString("\n")
}

// writeTable writes the parameter table of one plugin.
func writeTable(b *strings.Builder, params []param) {
	if len(params) == 0 {
		b.WriteString("No parameters.\n\n")
		return
	}

	b.WriteString("| Parameter | Required | Default | Description |\n")
	b.WriteString("|-----------|----------|---------|-------------|\n")

	for _, p := range params {
		fmt.Fprintf(b, "| %s | %s | %s | %s |\n",
			cell(codeSpan(p.name)), cell(requiredText(p)), cell(defaultText(p)), cell(docText(p)))
	}

	b.WriteString("\n")
}

func requiredText(p param) string {
	switch {
	case !p.required:
		return "no"
	case p.optionalTable != "":
		return "if " + codeSpan(p.optionalTable) + " is set"
	default:
		return "yes"
	}
}

func defaultText(p param) string {
	if !p.hasDefault {
		return "—"
	}

	if p.defaultVal == "" {
		return codeSpan(`""`)
	}

	return codeSpan(p.defaultVal)
}

func docText(p param) string {
	if strings.TrimSpace(p.doc) == "" {
		return noDescription
	}

	return p.doc
}

// heading is the heading text of a plugin, such as "Provider `regru`".
func heading(kind, name string) string {
	return kind + " " + codeSpan(name)
}

// anchor derives the fragment GitHub gives a heading: lower-cased, spaces as
// hyphens, everything but letters, digits, hyphens and underscores dropped.
func anchor(title string) string {
	var b strings.Builder

	for _, r := range strings.ToLower(title) {
		switch {
		case r == ' ':
			b.WriteByte('-')
		case r == '-' || r == '_' || r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r > 127:
			b.WriteRune(r)
		}
	}

	return b.String()
}

// codeSpan wraps text in a Markdown code span, using a longer delimiter when
// the text contains backticks itself.
func codeSpan(text string) string {
	if !strings.Contains(text, "`") {
		return "`" + text + "`"
	}

	return "`` " + text + " ``"
}

// cell makes text safe for a table cell: line breaks would end the row and a
// bare pipe would start a new column.
func cell(text string) string {
	text = strings.Join(strings.Fields(text), " ")

	return strings.ReplaceAll(text, "|", `\|`)
}

func sortedNames(plugins map[string]reflect.Type) []string {
	return slices.Sorted(maps.Keys(plugins))
}
