package main

import (
	"fmt"
	"strings"

	"github.com/dnspatch/dnspatch/plugin"
)

const (
	// header marks a file as ours; stale files carrying it are deleted.
	header = "// Code generated by cmd/genplugins; DO NOT EDIT."

	// noneTag leaves out every retriever and provider of the default build,
	// except the ones whose own tag is set.
	noneTag = "dnspatch_none"

	// fullTag compiles in every plugin, whatever else is set.
	fullTag = "full"

	catalogFile = "catalog_gen.go"

	tagsStart = "<!-- plugin-tags:start -->"
	tagsEnd   = "<!-- plugin-tags:end -->"
)

// constraint is the build constraint under which the plugin is compiled in.
// A plugin of the default build is on unless noneTag is set; one that the
// default build leaves out is on only for its own tag. fullTag brings both.
func constraint(p found) string {
	if p.Extra {
		return fullTag + " || " + p.Name
	}

	return "!" + noneTag + " || " + fullTag + " || " + p.Name
}

// fileName is the name of the file in package all that imports the plugin.
func fileName(p found) string {
	return string(p.Kind) + "_" + p.Name + ".go"
}

// renderImport is the file that imports one plugin under its build constraint.
func renderImport(p found) []byte {
	return []byte(fmt.Sprintf("%s\n\n//go:build %s\n\npackage all\n\nimport _ %q\n", header, constraint(p), p.Import))
}

// hint tells the user of a build without the plugin how to get it.
func hint(p found) string {
	if p.Extra {
		return fmt.Sprintf("rebuild with the %q or %q build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)", p.Name, fullTag)
	}

	return fmt.Sprintf("rebuild with the %q build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)", p.Name)
}

// renderCatalog is the file that declares every plugin to plugin.Default, so
// that a build without one can say what to do about it.
func renderCatalog(plugins []found) []byte {
	var b strings.Builder

	fmt.Fprintf(&b, "%s\n\npackage all\n\nimport \"github.com/dnspatch/dnspatch/plugin\"\n\n", header)
	b.WriteString("// Every plugin of the source tree is declared, whether or not this build\n")
	b.WriteString("// compiled it in: that is what lets a configuration that names a missing one\n")
	b.WriteString("// be told which build tag brings it.\n")
	b.WriteString("func init() {\n")

	for _, p := range plugins {
		method := "Declare"
		if p.Extra {
			method = "DeclareExtra"
		}

		fmt.Fprintf(&b, "\tplugin.Default.%s(plugin.%s, %q, %q)\n", method, kindConst(p.Kind), p.Name, hint(p))
	}

	b.WriteString("}\n")

	return []byte(b.String())
}

func kindConst(kind plugin.Kind) string {
	switch kind {
	case plugin.KindProvider:
		return "KindProvider"
	case plugin.KindRetriever:
		return "KindRetriever"
	default:
		return "KindNotifier"
	}
}

// renderTable is the table of build tags for docs/deployment/building.md.
func renderTable(plugins []found) string {
	var b strings.Builder

	b.WriteString("| Type | Kind | Build tag | In a plain build |\n")
	b.WriteString("|------|------|-----------|------------------|\n")

	for _, p := range plugins {
		inPlain := "yes"
		if p.Extra {
			inPlain = "no (`" + fullTag + "` brings it too)"
		}

		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s |\n", p.Name, p.Kind, p.Name, inPlain)
	}

	return b.String()
}

// replaceTable swaps the text between the markers of the page for table.
func replaceTable(doc, table string) (string, error) {
	start := strings.Index(doc, tagsStart)
	end := strings.Index(doc, tagsEnd)

	if start < 0 || end < start {
		return "", fmt.Errorf("the page has no %s ... %s block to put the table of build tags in", tagsStart, tagsEnd)
	}

	return doc[:start+len(tagsStart)] + "\n\n" + table + "\n" + doc[end:], nil
}
