// Code generated by cmd/genplugins; DO NOT EDIT.

package all

import "github.com/dnspatch/dnspatch/plugin"

// Every plugin of the source tree is declared, whether or not this build
// compiled it in: that is what lets a configuration that names a missing one
// be told which build tag brings it.
func init() {
	plugin.Default.DeclareExtra(plugin.KindNotifier, "mqtt", "rebuild with the \"mqtt\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindNotifier, "rabbitmq", "rebuild with the \"rabbitmq\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindNotifier, "redis", "rebuild with the \"redis\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindNotifier, "shoutrrr", "rebuild with the \"shoutrrr\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "beget", "rebuild with the \"beget\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "cloudflare", "rebuild with the \"cloudflare\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "duckdns", "rebuild with the \"duckdns\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "dyn", "rebuild with the \"dyn\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "dyndns2", "rebuild with the \"dyndns2\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "dynu", "rebuild with the \"dynu\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindProvider, "namecheap", "rebuild with the \"namecheap\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "nicru", "rebuild with the \"nicru\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "noip", "rebuild with the \"noip\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "regru", "rebuild with the \"regru\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindProvider, "rfc2136", "rebuild with the \"rfc2136\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "selectel", "rebuild with the \"selectel\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindProvider, "timeweb", "rebuild with the \"timeweb\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.DeclareExtra(plugin.KindProvider, "yandexcloud", "rebuild with the \"yandexcloud\" or \"full\" build tag, or use the -full image (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "2ip", "rebuild with the \"2ip\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "icanhazip", "rebuild with the \"icanhazip\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "identme", "rebuild with the \"identme\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "ifconfigco", "rebuild with the \"ifconfigco\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "interface", "rebuild with the \"interface\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
	plugin.Default.Declare(plugin.KindRetriever, "ipify", "rebuild with the \"ipify\" build tag (see https://dnspatch.github.io/dnspatch/deployment/building/)")
}
