// Package all registers the built-in plugins through blank imports, so that a
// single import makes them available to a command.
//
// Which plugins a build gets is decided by build tags. The plugins that are
// not marked with the //dnspatch:extra directive are all in unless the
// dnspatch_none tag is set; then a tag named after a plugin switches that one
// back on. A plugin marked extra, which is every notifier, since they pull in
// the client library of a broker, is out unless its own tag is set. The full
// tag switches on every plugin.
// The file that imports each plugin, and the catalog that declares them all to
// the registry, are generated by cmd/genplugins from the plugins/ tree; run
// go generate after adding a plugin.
//
// Library users should import the individual plugin packages they need
// instead, to avoid pulling in the dependencies of the others.
package all
